# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import upguard
from upguard.api.bulk_api import BulkApi  # noqa: E501
from upguard.rest import ApiException


class TestBulkApi(unittest.TestCase):
    """BulkApi unit test stubs"""

    def setUp(self):
        self.api = upguard.api.bulk_api.BulkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_deregister_hostnames(self):
        """Test case for bulk_deregister_hostnames

        Deregister a list of hostnames  # noqa: E501
        """
        pass

    def test_bulk_get_hostname_details(self):
        """Test case for bulk_get_hostname_details

        Get the details for a hostname  # noqa: E501
        """
        pass

    def test_bulk_get_hostnames_stats(self):
        """Test case for bulk_get_hostnames_stats

        Get statistics around registered bulk hostnames  # noqa: E501
        """
        pass

    def test_bulk_hostname_put_labels(self):
        """Test case for bulk_hostname_put_labels

        Assign new labels to a hostname  # noqa: E501
        """
        pass

    def test_bulk_list_hostnames(self):
        """Test case for bulk_list_hostnames

        List hostnames and their risks  # noqa: E501
        """
        pass

    def test_bulk_register_hostnames(self):
        """Test case for bulk_register_hostnames

        Register a list of hostnames to be scanned for risks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
