# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import upguard
from upguard.api.subsidiaries_api import SubsidiariesApi  # noqa: E501
from upguard.rest import ApiException


class TestSubsidiariesApi(unittest.TestCase):
    """SubsidiariesApi unit test stubs"""

    def setUp(self):
        self.api = upguard.api.subsidiaries_api.SubsidiariesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subsidiaries(self):
        """Test case for subsidiaries

        Get a list of subsidiaries  # noqa: E501
        """
        pass

    def test_subsidiary_domain_details(self):
        """Test case for subsidiary_domain_details

        Retrieve details for a domain  # noqa: E501
        """
        pass

    def test_subsidiary_domain_update_labels(self):
        """Test case for subsidiary_domain_update_labels

        Assign labels to an domain  # noqa: E501
        """
        pass

    def test_subsidiary_domains(self):
        """Test case for subsidiary_domains

        List subsidiary domains  # noqa: E501
        """
        pass

    def test_subsidiary_ip_details(self):
        """Test case for subsidiary_ip_details

        Retrieve details for an IP address  # noqa: E501
        """
        pass

    def test_subsidiary_ip_update_labels(self):
        """Test case for subsidiary_ip_update_labels

        Assign labels to an IP  # noqa: E501
        """
        pass

    def test_subsidiary_ips(self):
        """Test case for subsidiary_ips

        List subdiary ips  # noqa: E501
        """
        pass

    def test_subsidiary_ranges(self):
        """Test case for subsidiary_ranges

        List subsidiary ip ranges  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
