# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from upguard.api_client import ApiClient


class SubsidiariesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def subsidiaries(self, **kwargs):  # noqa: E501
        """Get a list of subsidiaries  # noqa: E501

        Returns a list of subsidiaries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiaries(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: GetSubsidiariesV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiaries_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.subsidiaries_with_http_info(**kwargs)  # noqa: E501
            return data

    def subsidiaries_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of subsidiaries  # noqa: E501

        Returns a list of subsidiaries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiaries_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: GetSubsidiariesV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiaries" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiaries', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetSubsidiariesV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_domain_details(self, subsidiary_primary_hostname, hostname, **kwargs):  # noqa: E501
        """Retrieve details for a domain  # noqa: E501

        Returns the details for a domain. It will return 422 when requesting details of an inactive domain.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domain_details(subsidiary_primary_hostname, hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show the domain detail for. (required)
        :param str hostname: The hostname for which to return the details, e.g. \"upguard.com\" (required)
        :return: GetDomainDetailsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_domain_details_with_http_info(subsidiary_primary_hostname, hostname, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_domain_details_with_http_info(subsidiary_primary_hostname, hostname, **kwargs)  # noqa: E501
            return data

    def subsidiary_domain_details_with_http_info(self, subsidiary_primary_hostname, hostname, **kwargs):  # noqa: E501
        """Retrieve details for a domain  # noqa: E501

        Returns the details for a domain. It will return 422 when requesting details of an inactive domain.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domain_details_with_http_info(subsidiary_primary_hostname, hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show the domain detail for. (required)
        :param str hostname: The hostname for which to return the details, e.g. \"upguard.com\" (required)
        :return: GetDomainDetailsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'hostname']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_domain_details" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_domain_details`")  # noqa: E501
        # verify the required parameter 'hostname' is set
        if self.api_client.client_side_validation and ('hostname' not in params or
                                                       params['hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `hostname` when calling `subsidiary_domain_details`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'hostname' in params:
            query_params.append(('hostname', params['hostname']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/domain', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetDomainDetailsV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_domain_update_labels(self, subsidiary_primary_hostname, hostname, labels, **kwargs):  # noqa: E501
        """Assign labels to an domain  # noqa: E501

        Assign labels to a domain. To remove all labels pass an empty list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domain_update_labels(subsidiary_primary_hostname, hostname, labels, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to update the domain labels for. (required)
        :param int hostname: The hostname to update labels for (required)
        :param list[str] labels: The labels to assign to the domain. You can pass an empty array to remove all labels. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_domain_update_labels_with_http_info(subsidiary_primary_hostname, hostname, labels, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_domain_update_labels_with_http_info(subsidiary_primary_hostname, hostname, labels, **kwargs)  # noqa: E501
            return data

    def subsidiary_domain_update_labels_with_http_info(self, subsidiary_primary_hostname, hostname, labels, **kwargs):  # noqa: E501
        """Assign labels to an domain  # noqa: E501

        Assign labels to a domain. To remove all labels pass an empty list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domain_update_labels_with_http_info(subsidiary_primary_hostname, hostname, labels, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to update the domain labels for. (required)
        :param int hostname: The hostname to update labels for (required)
        :param list[str] labels: The labels to assign to the domain. You can pass an empty array to remove all labels. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'hostname', 'labels']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_domain_update_labels" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_domain_update_labels`")  # noqa: E501
        # verify the required parameter 'hostname' is set
        if self.api_client.client_side_validation and ('hostname' not in params or
                                                       params['hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `hostname` when calling `subsidiary_domain_update_labels`")  # noqa: E501
        # verify the required parameter 'labels' is set
        if self.api_client.client_side_validation and ('labels' not in params or
                                                       params['labels'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `labels` when calling `subsidiary_domain_update_labels`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'hostname' in params:
            query_params.append(('hostname', params['hostname']))  # noqa: E501
        if 'labels' in params:
            query_params.append(('labels', params['labels']))  # noqa: E501
            collection_formats['labels'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/domain/labels', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_domains(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subsidiary domains  # noqa: E501

        Returns a list of domains for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domains(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show domains for. (required)
        :param bool active: Retrieve active domains
        :param bool inactive: Retrieve inactive domains
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the domains by  If not specified will default to `domain` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetDomainsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_domains_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_domains_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
            return data

    def subsidiary_domains_with_http_info(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subsidiary domains  # noqa: E501

        Returns a list of domains for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_domains_with_http_info(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show domains for. (required)
        :param bool active: Retrieve active domains
        :param bool inactive: Retrieve inactive domains
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the domains by  If not specified will default to `domain` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetDomainsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'active', 'inactive', 'labels', 'page_token', 'page_size', 'sort_by', 'sort_desc']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_domains" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_domains`")  # noqa: E501

        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] > 2000):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_domains`, must be a value less than or equal to `2000`")  # noqa: E501
        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] < 10):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_domains`, must be a value greater than or equal to `10`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'active' in params:
            query_params.append(('active', params['active']))  # noqa: E501
        if 'inactive' in params:
            query_params.append(('inactive', params['inactive']))  # noqa: E501
        if 'labels' in params:
            query_params.append(('labels', params['labels']))  # noqa: E501
            collection_formats['labels'] = 'multi'  # noqa: E501
        if 'page_token' in params:
            query_params.append(('page_token', params['page_token']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_desc' in params:
            query_params.append(('sort_desc', params['sort_desc']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/domains', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetDomainsV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_ip_details(self, subsidiary_primary_hostname, ip, **kwargs):  # noqa: E501
        """Retrieve details for an IP address  # noqa: E501

        Returns the details of the IP address. It will return 422 when requesting details of an inactive IP address.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ip_details(subsidiary_primary_hostname, ip, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show the IP detail for. (required)
        :param str ip: The IP address to get details for (required)
        :return: GetIpDetailsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_ip_details_with_http_info(subsidiary_primary_hostname, ip, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_ip_details_with_http_info(subsidiary_primary_hostname, ip, **kwargs)  # noqa: E501
            return data

    def subsidiary_ip_details_with_http_info(self, subsidiary_primary_hostname, ip, **kwargs):  # noqa: E501
        """Retrieve details for an IP address  # noqa: E501

        Returns the details of the IP address. It will return 422 when requesting details of an inactive IP address.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ip_details_with_http_info(subsidiary_primary_hostname, ip, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show the IP detail for. (required)
        :param str ip: The IP address to get details for (required)
        :return: GetIpDetailsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'ip']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_ip_details" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_ip_details`")  # noqa: E501
        # verify the required parameter 'ip' is set
        if self.api_client.client_side_validation and ('ip' not in params or
                                                       params['ip'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ip` when calling `subsidiary_ip_details`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'ip' in params:
            query_params.append(('ip', params['ip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/ip', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetIpDetailsV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_ip_update_labels(self, subsidiary_primary_hostname, ip, labels, **kwargs):  # noqa: E501
        """Assign labels to an IP  # noqa: E501

        Assign labels to an IP. To remove all labels pass an empty list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ip_update_labels(subsidiary_primary_hostname, ip, labels, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to update the IP labels for. (required)
        :param int ip: The IP to update labels for (required)
        :param list[str] labels: The labels to assign to the IP. You can pass an empty array to remove all labels. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_ip_update_labels_with_http_info(subsidiary_primary_hostname, ip, labels, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_ip_update_labels_with_http_info(subsidiary_primary_hostname, ip, labels, **kwargs)  # noqa: E501
            return data

    def subsidiary_ip_update_labels_with_http_info(self, subsidiary_primary_hostname, ip, labels, **kwargs):  # noqa: E501
        """Assign labels to an IP  # noqa: E501

        Assign labels to an IP. To remove all labels pass an empty list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ip_update_labels_with_http_info(subsidiary_primary_hostname, ip, labels, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to update the IP labels for. (required)
        :param int ip: The IP to update labels for (required)
        :param list[str] labels: The labels to assign to the IP. You can pass an empty array to remove all labels. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'ip', 'labels']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_ip_update_labels" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_ip_update_labels`")  # noqa: E501
        # verify the required parameter 'ip' is set
        if self.api_client.client_side_validation and ('ip' not in params or
                                                       params['ip'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ip` when calling `subsidiary_ip_update_labels`")  # noqa: E501
        # verify the required parameter 'labels' is set
        if self.api_client.client_side_validation and ('labels' not in params or
                                                       params['labels'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `labels` when calling `subsidiary_ip_update_labels`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'ip' in params:
            query_params.append(('ip', params['ip']))  # noqa: E501
        if 'labels' in params:
            query_params.append(('labels', params['labels']))  # noqa: E501
            collection_formats['labels'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/ip/labels', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_ips(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subdiary ips  # noqa: E501

        Returns a list of ips for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ips(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show ips for. (required)
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the IPs by  If not specified will default to `ip` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetIPsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_ips_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_ips_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
            return data

    def subsidiary_ips_with_http_info(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subdiary ips  # noqa: E501

        Returns a list of ips for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ips_with_http_info(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show ips for. (required)
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the IPs by  If not specified will default to `ip` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetIPsV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'labels', 'page_token', 'page_size', 'sort_by', 'sort_desc']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_ips" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_ips`")  # noqa: E501

        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] > 2000):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_ips`, must be a value less than or equal to `2000`")  # noqa: E501
        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] < 10):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_ips`, must be a value greater than or equal to `10`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'labels' in params:
            query_params.append(('labels', params['labels']))  # noqa: E501
            collection_formats['labels'] = 'multi'  # noqa: E501
        if 'page_token' in params:
            query_params.append(('page_token', params['page_token']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_desc' in params:
            query_params.append(('sort_desc', params['sort_desc']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/ips', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetIPsV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def subsidiary_ranges(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subsidiary ip ranges  # noqa: E501

        Returns a list of ip ranges for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ranges(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show ranges for. (required)
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the IP ranges by  If not specified will default to `num_ips` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetRangesV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.subsidiary_ranges_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
        else:
            (data) = self.subsidiary_ranges_with_http_info(subsidiary_primary_hostname, **kwargs)  # noqa: E501
            return data

    def subsidiary_ranges_with_http_info(self, subsidiary_primary_hostname, **kwargs):  # noqa: E501
        """List subsidiary ip ranges  # noqa: E501

        Returns a list of ip ranges for a subsidiary.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.subsidiary_ranges_with_http_info(subsidiary_primary_hostname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subsidiary_primary_hostname: The primary hostname of the subsidiary to show ranges for. (required)
        :param list[str] labels: Filter result by the provided labels
        :param str page_token: The `page_token` from a previous request, use this to get the next page of results.
        :param int page_size: The number of results to return per page.
        :param str sort_by: The value to sort the IP ranges by  If not specified will default to `num_ips` and set `sort_desc` to `true`
        :param bool sort_desc: Whether or not to sort the results in descending order
        :return: GetRangesV1RespBody
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subsidiary_primary_hostname', 'labels', 'page_token', 'page_size', 'sort_by', 'sort_desc']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method subsidiary_ranges" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subsidiary_primary_hostname' is set
        if self.api_client.client_side_validation and ('subsidiary_primary_hostname' not in params or
                                                       params['subsidiary_primary_hostname'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `subsidiary_primary_hostname` when calling `subsidiary_ranges`")  # noqa: E501

        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] > 2000):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_ranges`, must be a value less than or equal to `2000`")  # noqa: E501
        if self.api_client.client_side_validation and ('page_size' in params and params['page_size'] < 10):  # noqa: E501
            raise ValueError("Invalid value for parameter `page_size` when calling `subsidiary_ranges`, must be a value greater than or equal to `10`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subsidiary_primary_hostname' in params:
            query_params.append(('subsidiary_primary_hostname', params['subsidiary_primary_hostname']))  # noqa: E501
        if 'labels' in params:
            query_params.append(('labels', params['labels']))  # noqa: E501
            collection_formats['labels'] = 'multi'  # noqa: E501
        if 'page_token' in params:
            query_params.append(('page_token', params['page_token']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_desc' in params:
            query_params.append(('sort_desc', params['sort_desc']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API key in header']  # noqa: E501

        return self.api_client.call_api(
            '/subsidiary/ranges', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetRangesV1RespBody',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
