# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import upguard
from upguard.api.ips_api import IpsApi  # noqa: E501
from upguard.rest import ApiException


class TestIpsApi(unittest.TestCase):
    """IpsApi unit test stubs"""

    def setUp(self):
        self.api = upguard.api.ips_api.IpsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_custom_ips(self):
        """Test case for add_custom_ips

        Add custom ips  # noqa: E501
        """
        pass

    def test_ip_details(self):
        """Test case for ip_details

        Retrieve details for an IP address  # noqa: E501
        """
        pass

    def test_ip_update_labels(self):
        """Test case for ip_update_labels

        Assign labels to an IP  # noqa: E501
        """
        pass

    def test_ips(self):
        """Test case for ips

        Get a list of ips  # noqa: E501
        """
        pass

    def test_ranges(self):
        """Test case for ranges

        Get a list of ip ranges  # noqa: E501
        """
        pass

    def test_remove_custom_ips(self):
        """Test case for remove_custom_ips

        Remove custom ips  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
