# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import upguard
from upguard.api.dataleaks_api import DataleaksApi  # noqa: E501
from upguard.rest import ApiException


class TestDataleaksApi(unittest.TestCase):
    """DataleaksApi unit test stubs"""

    def setUp(self):
        self.api = upguard.api.dataleaks_api.DataleaksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dataleaks_disclosures(self):
        """Test case for dataleaks_disclosures

        Get a list of disclosures  # noqa: E501
        """
        pass

    def test_dataleaks_disclosures_update_status(self):
        """Test case for dataleaks_disclosures_update_status

        Update the status of a disclosure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
