# coding: utf-8

"""
    UpGuard CyberRisk API

    Access information from the CyberRisk platform programmatically using this API.  You can find or generate an API key to access this API in your CyberRisk Account Settings. Please authorize all requests by setting the \"Authorization\" header to your api key.  The base url for all public endpoints is https://cyber-risk.upguard.com/api/public  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import upguard
from upguard.api.typosquat_api import TyposquatApi  # noqa: E501
from upguard.rest import ApiException


class TestTyposquatApi(unittest.TestCase):
    """TyposquatApi unit test stubs"""

    def setUp(self):
        self.api = upguard.api.typosquat_api.TyposquatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_typosquat_domains(self):
        """Test case for list_typosquat_domains

        List typosquat domains  # noqa: E501
        """
        pass

    def test_typosquat_details(self):
        """Test case for typosquat_details

        Retrieve typosquat details for a domain.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
